name: ai_model_evaluation_mlops
services:
  airflow:
    image: apache/airflow:latest
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@localhost:5432/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
  mlflow:
    image: mlflow/mlflow
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/opt/mlflow/mlruns

